### ISSUE TITLE
项目生成报错

### ISSUE THREAD

**Issue by github-wuzhenghui** [Easy-doc/Easy-doc-core#4]
您好，我使用了您的工具，但是目前报错，具体情况如下：

项目为Spring boot，使用maven引入，代码如下：

<dependency>
            <groupId>com.stalary</groupId>
            <artifactId>easy-doc</artifactId>
            <version>1.3.5</version>
        </dependency>

yml配置如下：
com:
  stalary:
    easydoc:
      name: easydoc demo # 项目名称
      contact: stalary@613.com # 项目联系人
      description: easydoc测试项目 # 项目描述
      path: org.yuxin # 解析的包路径(包括data和controller的包)
      open: true # 是否开启文档功能
      source: true # 是否读取源码,false则为读取resources中的easydoc.txt

项目目录结构如下：

<img width="491" alt="微信图片_20200929221136" src="https://user-images.githubusercontent.com/23286664/94569871-c6e74400-02a0-11eb-89de-c77dfa81e122.png">

请帮忙看看是哪儿使用错了吗？

**Comment by stalary** [comment]
已解决
